kafka:
  bootstrapServers:
    - 127.0.0.1:9092
  consumerGroupId: "why-groovy"
  autoOffsetReset: "latest"

# Main topic to sink to pg
topic:
  name: demo_java

# Quarantine strategy
quarantine:
  topicName: demo_java_quarantine
  maxRetries: 3

# Dead letter queuing
deadletter:
  topicName: demo_java_dlq


postgres:
  host: localhost
  dbName: djangopg
  user: postgres
  password: mysecretpassword
  table: main_payment
  schema:
    - name: id
      type: string
    - name: time
      type: timestamp
    - name: amount
      type: number
